# Generated by Django 2.2.4 on 2021-05-05 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0003_auto_20210506_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attandencetable',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 5, 6, 0, 10, 31, 637878)),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2021, 5, 6, 0, 10, 31, 636880)),
        ),
    ]
